debug: :6060
listen: 127.0.0.1:6000
storage:
  drive: local
  option:
    path: ./public
#  drive: oss
#  option:
#    endpoint: http://oss-cn-shenzhen.aliyuncs.com
#    access_key_id:
#    access_key_secret:
#    bucket_name: